//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_notificaciones
    {
        public int not_id { get; set; }
        public Nullable<int> per_id { get; set; }
        public Nullable<System.DateTime> not_fecha { get; set; }
        public string not_descripcion { get; set; }
    
        public virtual t_persona t_persona { get; set; }
    }
}
