//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_persona()
        {
            this.t_notificaciones = new HashSet<t_notificaciones>();
            this.t_pedido = new HashSet<t_pedido>();
            this.t_venta = new HashSet<t_venta>();
        }
    
        public int per_id { get; set; }
        public Nullable<int> ciu_id { get; set; }
        public string per_nombre { get; set; }
        public string per_direccion { get; set; }
        public string per_telefono { get; set; }
        public string per_cuenta_bancaria { get; set; }
        public string per_correo { get; set; }
        public Nullable<int> per_nit { get; set; }
        public string per_tipo { get; set; }
        public string per_tipo_documento { get; set; }
        public string per_tipo_cuenta { get; set; }
    
        public virtual t_ciudad t_ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_notificaciones> t_notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_pedido> t_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_venta> t_venta { get; set; }
    }
}
