//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_venta()
        {
            this.t_detalle_venta = new HashSet<t_detalle_venta>();
        }
    
        public int ven_id { get; set; }
        public Nullable<int> per_id { get; set; }
        public Nullable<int> usu_id { get; set; }
        public Nullable<System.DateTime> ven_fecha { get; set; }
        public string ven_metodo_pago { get; set; }
        public Nullable<long> ven_total { get; set; }
        public Nullable<long> ven_numero_transaccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_detalle_venta> t_detalle_venta { get; set; }
        public virtual t_persona t_persona { get; set; }
        public virtual t_usuario t_usuario { get; set; }
    }
}
